
# fastcgi_cache_path /etc/nginx/cache levels=1:2 keys_zone=MYAPP:100m inactive=60m;
# fastcgi_cache_key "$scheme$request_method$host$request_uri";

server {
    listen       80;
    http2 on;
    server_name  localhost;
    root /var/www/html/public;
    index index.php;

    client_max_body_size 40M;

    #access_log  /var/log/nginx/host.access.log  main;

    location ~ \.js\.gzip$ {
        add_header Content-Encoding gzip;
        gzip off;
        types { text/javascript gzip; }
    }

    location ~ \.css\.gzip$ {
        add_header Content-Encoding gzip;
        gzip off;
        types { text/css gzip; }
    }

    # disallow access to .htaccess files, if Apache's document root concurs with nginx's one
    location ~ /\.ht {
        deny all;
    }

    if (!-e $request_filename) {
        rewrite ^/(.+)\.(\d+)\.(php|js|css|png|jpg|gif|gzip)$ /$1.$3 last;
    }

    # Block access to composer files
    location ~* composer\.(?:json|lock) {
        deny all;
    }


    location ~* \.(css)$ {
        expires 1M;
    }

    location ~* \.(ico)$ {
        expires 1w;
    }

    location ~* \.(js)$ {
        expires 1M;
    }

    location ~* \.(ogg|bmp|gif|jpeg|jpg|png|svg|webp|mp4|ogg|webm)$ {
        expires 1M;
    }

    location ~* \.(eot|otf|ttf|woff|woff2)$ {
        expires 1M;
    }

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ ^/(index\.php)$ {
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        if (!-f $document_root$fastcgi_script_name) {
            return 404;
        }
        fastcgi_buffer_size 32k;
        fastcgi_buffers 16 16k;
        fastcgi_connect_timeout 240s;
        fastcgi_read_timeout 240s;
        fastcgi_send_timeout 240s;
        fastcgi_pass         web:9000;
        fastcgi_index        index.php;
        include              fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;

        # fastcgi_cache MYAPP;
        # fastcgi_cache_valid 200 60m;
    }
    # Deny all other PHP files
    location ~ \.php$ {
        deny all;
    }

}
